services:

  trojan:
    #image: trojangfw/trojan
    image: gists/trojan-go
    command: trojan-go -config /config/config.json
    restart: always
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - "./nginx/cert.crt:/etc/cert.crt"
      - "./nginx/key.key:/etc/key.key"
      - "./trojan/config.json:/config/config.json"
      - "./trojan/geoip.dat:/geoip"
  xray:
    #image: trojangfw/trojan
    image: teddysun/xray
    restart: always
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - "./nginx/cert.crt:/etc/cert.crt"
      - "./nginx/key.key:/etc/key.key"
      - "./xray/config.json:/etc/xray/config.json"
      - "./trojan/geoip.dat:/usr/share/xray/geoip.dat"
      - "./trojan/geosite.dat:/usr/share/xray/geosite.dat"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/myconfig.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/index.html:/usr/share/nginx/html/index.html"
    networks:
      - app-network
    logging:
      options:
        max-size: "50m"
        max-file: "5"
  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    # и снова мониторуем директорию nginx
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      # задаем переменные среды
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

  dnstt-server:
    container_name: dnstt-server
    image: ghcr.io/kbnchk/dnstt-server:latest
    command: ["-udp", ":5300", "-privkey-file", "/keys/server.key", "t.nfw1.online" , "host.docker.internal:22"]
    ports:
      - "53:5300/udp"
    volumes:
      - ./dnstt:/keys
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  warp:
    image: caomingjun/warp
    restart: always
    ports:
      - "1080:1080"
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge
