root /usr/share/nginx/html;

server {
                listen   0.0.0.0:80;

				# URL certbot'a, где он будет слушать входящие
				# подключения во время выдачи SSL
                location /.well-known {
                        proxy_pass http://172.17.0.1:6000;
                }
		location / {
			index index.html;
		}
		location /salo {
			index salo.html;
		}
		location /uaz {
			index uaz.html;
		}
        }


server {
	listen   0.0.0.0:8443;

	server_name abghdh.duckdns.org;

    ssl_certificate /etc/cert.crt;
    ssl_certificate_key /etc/key.key;

    # Supported secure protocols
    ssl_protocols TLSv1.2 TLSv1.3;


	location / {
			index index.html;
		}
		location /salo {
			index salo.html;
		}
		location /uaz {
			index uaz.html;
		}
        }
}