root /usr/share/nginx/html;

server {
                listen   0.0.0.0:80;

				# URL certbot'a, где он будет слушать входящие
				# подключения во время выдачи SSL
                location /.well-known {
                        proxy_pass http://172.17.0.1:6000;
                }
		location / {
			index index.html;
		}
		location /salo {
			index salo.html;
		}
		location /uaz {
			index uaz.html;
		}
        }
